 
# 配置目标：
    # - 通过配置文件设置日志输出，可以选择后台文件输出和控制台输出
    # - 默认：后台日志文件输出
    # - 配置文件里设置开关打开：控制台和后台日志文件一起输出

daemonMode: true  # 是否以守护进程模式运行，true 则脱离终端，false 则保持在前台

# 日志配置
log_console: false           # true 则控制台和文件一起输出（调试使用）；false 仅文件输出
level: "info"               # 文件输出的最低日志级别
pattern: "[%Y-%m-%d %H:%M:%S.%e] [%l] [%s:%#] [%t] %v" #日志格式模式：[年-月-日 时:分:秒.毫秒] [日志级别] [源文件:行号] [线程ID] 实际日志消息
filename: "logs/myservice.log"    # 日志文件路径
immediate_flush: true # 是否立即刷新到磁盘

# 滚动配置

max_size: 10  # 按大小滚动配置，单个文件最大 10KB
max_files: 3  # 最大保留 3 个文件
